### ISSUE TITLE
Proposal: Conventions for README and LICENSE

### ISSUE THREAD

**Issue by technosophos** [deislabs/hippo-cli#21]
I would like to propose a convention for Hippo bindles in general, but with support in HIPPOFACTS (as you see fit):

I think we should have "reserved" parcels for README and LICENSE data. We could do this either by treating the parcel name `README`|`LICENSE` as special, or by creating `readme` and `license` groups.

The purpose of the README would be to provide user-facing information for the person _running the bindle_. For example, we could take that data and display it in `hippo` or in a search results page for a fabled Bindle UI.

The purpose of LICENSE is more legal: We want to conventionally specify how to figure out what license is attached to a bindle.

Note that it would be desirable to not specify the text format of the file in the file's name. So a user could choose markdown (`README.md`), text (`README.txt`), or another format. Conceivably, we could support multiple file formats if we used groups:

```toml
[[group]]
name = "license"

[[parcel]]
label.name = "LICENSE.txt"
label.mediaType = "text/plain"
conditions.memberOf = ["license"]

[[parcel]]
label.name = "LICENSE.pdf"
label.mediaType = "application/why-would-you-do-this"
conditions.memberOf = ["license"]
```

A user agent could then select the file according to its own criteria
