### ISSUE TITLE
Discussion: obviate need for duplicate route prefix

### ISSUE THREAD

**Issue by itowlson** [deislabs/hippo-cli#39]
Consider the following handler:

```toml
[[handler]]
route = "/images/..."
external.bindleId = "fileserver/0.3.0"
external.handlerId = "static"
files = ["images/*.jpg"]
```

Because the linked files have the prefix `images`, and are served from the `/images` URL, they need to be addressed as `http://.../images/images/cassowary.jpg`.  This is surprising; and vexing, because when the dev is testing against their local filesystem, the files won't have the double prefix.

We should consider options for making this less surprising and less vexing, ideally "intelligently" (that is, without requiring the developer to specify their desired behaviour) while still predictably.  We may also need to support an override for when our intelligent behaviour turns out to be stupid after all.

Currently I am thinking of the rule:

* If you are in a wildcard route, and any prefix of a `files` pattern matches the route prefix, then that prefix is dropped.

This works nicely for typical static file serving cases.  However I would like to talk more about possible other cases where this might break down, or is surprising.  For example, what would you expect to happen here"

```toml
[[handler]]
route = "/images/..."
files = ["images/*.jpg", "photos/*.jpg"]
```

What about scenarios other than static file serving?
